version: '3'
services:
    proxy:
        container_name: proxy
        restart: always
        image: nginxproxy/nginx-proxy:1.4
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ./certs:/etc/nginx/certs
            - /etc/nginx/vhost.d
            - ./config/nginx.conf:/etc/nginx/nginx.conf
        networks:
            - nginx-proxy-network
            
    proxy-companion:
        container_name: proxy-companion
        restart: always
        image: sebastienheyd/self-signed-proxy-companion
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./certs:/etc/nginx/certs
        environment:
            - EXPIRATION=398
        networks:
            - nginx-proxy-network

networks:
    nginx-proxy-network:
        external: true
